oauth2-proxy:
#  fullnameOverride: "oauth2-proxy"
  service:
    portNumber: 4180
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "4096m"

  hosts:
    - host: CHANGEME
      paths:
        - /test